# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Acme-Greek
version:      1.0
version_from: lib/Acme/Greek.pm
installdirs:  site
license: perl
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
